CREATE TABLE bmc.t_device (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  description TEXT,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(255) DEFAULT 'system',
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(255) DEFAULT 'system',
  version INT DEFAULT 0
);

CREATE TABLE bmc.c_warehouse (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  description TEXT,
  location VARCHAR(255)
);

CREATE TABLE bmc.t_box (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(32) NOT NULL,
  description TEXT,
  renter_id VARCHAR(32) NOT NULL,
  device_id BIGINT,
  warehouse_id BIGINT NOT NULL,
  lower_humidity_limit DECIMAL,
  upper_humidity_limit DECIMAL,
  lower_temperature_limit DECIMAL,
  upper_temperature_limit DECIMAL,
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  created_by VARCHAR(255) DEFAULT 'system',
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
  updated_by VARCHAR(255) DEFAULT 'system',
  version INT DEFAULT 0,
  CONSTRAINT fk_device FOREIGN KEY (device_id) REFERENCES bmc.t_device(id),
  CONSTRAINT fk_warehouse FOREIGN KEY (warehouse_id) REFERENCES bmc.c_warehouse(id)
);